from __future__ import annotations

import json
import keyword
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_DIR = ROOT / "schemas" / "v1"
GENERATED_DIR = ROOT / "src" / "l9_harness" / "contracts" / "generated"
HEADER = "# Generated by scripts/generate_bindings.py; do not edit.\n"


def ruff_format(source: str) -> str:
    # Generated output must already satisfy `ruff check .` and
    # `ruff format --check .` (separate, earlier CI steps): running it
    # through ruff here keeps the generator's raw rendering and the repo's
    # lint/formatting rules from fighting each other (each pass previously
    # undid the other's changes).
    fixed = subprocess.run(
        [sys.executable, "-m", "ruff", "check", "--fix", "--exit-zero", "-"],
        input=source,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    return subprocess.run(
        [sys.executable, "-m", "ruff", "format", "-"],
        input=fixed,
        capture_output=True,
        text=True,
        check=True,
    ).stdout


def class_name(value: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", value)
    candidate = "".join(part[:1].upper() + part[1:] for part in parts if part)
    if not candidate or candidate[0].isdigit():
        candidate = "Schema" + candidate
    return candidate + "Document"


def safe_key(value: str) -> str:
    if value.isidentifier() and not keyword.iskeyword(value):
        return value
    return repr(value)


def load_schemas() -> list[tuple[Path, dict[str, object]]]:
    records: list[tuple[Path, dict[str, object]]] = []
    for path in sorted(SCHEMA_DIR.glob("*.schema.json")):
        if path.name == "registry.json":
            continue
        records.append((path, json.loads(path.read_text(encoding="utf-8"))))
    return records


def render_inventory(records: list[tuple[Path, dict[str, object]]]) -> str:
    items = {path.stem.replace(".schema", ""): str(document["$id"]) for path, document in records}
    return HEADER + "SCHEMAS = " + repr(items) + "\n"


def render_models(records: list[tuple[Path, dict[str, object]]]) -> str:
    lines = [
        HEADER.rstrip(),
        "from __future__ import annotations",
        "",
        "from typing import NotRequired, Required, TypeAlias, TypedDict",
        "",
        "JSONScalar: TypeAlias = str | int | float | bool | None",
        'JSONValue: TypeAlias = JSONScalar | list["JSONValue"] | dict[str, "JSONValue"]',
        "",
    ]
    exports: list[str] = []
    for path, document in records:
        title = str(document.get("title") or path.stem.replace(".schema", ""))
        name = class_name(title)
        exports.append(name)
        properties = document.get("properties")
        required = set(document.get("required") or [])
        if not isinstance(properties, dict) or not properties:
            lines.append(f"{name} = TypedDict({name!r}, {{}}, total=False)")
        else:
            fields = []
            for key in sorted(properties):
                wrapper = "Required" if key in required else "NotRequired"
                fields.append(f"{str(key)!r}: {wrapper}[JSONValue]")
            lines.append(f"{name} = TypedDict({name!r}, {{{', '.join(fields)}}}, total=False)")
        lines.append("")
    lines.append("__all__ = [")
    lines.extend(f"    {name!r}," for name in ["JSONScalar", "JSONValue", *exports])
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    records = load_schemas()
    outputs = {
        GENERATED_DIR / "schema_inventory.py": render_inventory(records),
        GENERATED_DIR / "models.py": render_models(records),
    }
    for path, content in outputs.items():
        path.write_text(ruff_format(content), encoding="utf-8", newline="\n")
        print(path)


if __name__ == "__main__":
    main()
